networks:
  sentinel-net:
    driver: bridge

services:

  postgres:
    image: postgres:15-alpine
    container_name: sentinel-db
    networks:
      - sentinel-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - sentinel-net
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    networks:
      - sentinel-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://0.0.0.0:29092,LISTENER_DOCKER_EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:29092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - sentinel-net
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka

  redis:
    image: redis:alpine
    networks:
      - sentinel-net
    ports:
      - "6379:6379"
  
  analyzer:
    build: ./analyzer-service
    container_name: sentinel-analyzer-service
    networks:
      - sentinel-net
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sentinel_db
    depends_on:
      - kafka
      - redis
      - postgres

  dashboard:
    build: ./sentinel-dashboard
    container_name: sentinel-dashboard-ui
    ports:
      - "3000:3000"
    networks:
      - sentinel-net
    depends_on:
      - analyzer

  sniffer:
    build: ./py-scripts
    container_name: sentinel-sniffer
    network_mode: "host" # Gerçek ağ paketlerini yakalamak için host mode şart
    environment:
      - KAFKA_SERVER=localhost:9092 # Host mode kullandığı için localhost
    depends_on:
      - kafka
  ai-worker:
    build: ./py-scripts
    container_name: sentinel-ai-worker
    command: python sentinel_ai_worker.py
    networks:
      - sentinel-net
    environment:
      # Docker içinde Kafka'ya servis ismiyle erişiriz
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka

volumes:
  postgres_data:

